### ISSUE TITLE
Test case for html

### ISSUE THREAD

**Issue by ovatsus** [colinbull/FSharpEnt#5]
With Html Agility Pack, on this [html document](https://gist.github.com/ovatsus/8047364) getting the first and only `ul`, and then calling `.Elements("li")` on it, only returns the first element. Calling `.Descendants("li")` on the document works fine, though. The reason is probably because some `li` tags are closed as `il`. I'm thinking of replacing HAP with the html parser in FSharpEnt. Will it handle this case better? I'm not even sure the `il` is valid html, but it's a real web page that browsers handle fine

**Comment by colinbull** [comment]
Closed, because this has been moved to FSharp.Data
